---

- hosts: all
  remote_user: wal
  vars:
    app: "pixel"
    app_dir: "/home/wal/pixel"
    node_name: "pixel"

  tasks:
    - name: patch sudoers file (1/2)
      sudo: yes
      lineinfile: 
          dest=/etc/sudoers
          regexp="^Defaults\tenv_reset" state=absent 

    - name: patch sudoers file (2/2)
      sudo: yes
      lineinfile: 
          dest=/etc/sudoers
          regexp="^Defaults\tsecure_path" state=absent 

    - name: stop application
      sudo: yes
      ignore_errors: yes
      shell: chdir={{ app_dir }} export PATH=$PATH:/usr/lib/erlang/bin && {{ app_dir }}/release/bin/{{ app }} stop

    - name: ensure log directory exists
      file: dest={{ app_dir }}/log state=directory

    - name: ensure log_archive directory exists
      file: dest={{ app_dir }}/log_archive state=directory

    - name: ensure bin directory exists
      file: dest={{ app_dir }}/bin state=directory

    - name: remove release directory and all its files
      file: dest={{ app_dir }}/release state=absent

    - name: create release directory
      file: dest={{ app_dir }}/release state=directory

    - name: copy and unpack the release
      unarchive: src=_rel/pixel-1.tar.gz dest={{ app_dir }}/release

    - name: template monitor script out to destination server 
      template: src=j2/monitor.j2 dest={{ app_dir }}/bin/monitor mode=755

    - name: template vm.args.j2 out to destination server 
      template: src=j2/vm.args.j2 dest={{ app_dir }}/release/releases/1/vm.args

    - name: launch application
      sudo: yes
      shell: chdir={{ app_dir }} export export PATH=$PATH:/usr/lib/erlang/bin && {{ app_dir }}/release/bin/{{ app }} start


