#!/bin/sh
apps="sync,ranch,crypto,cowlib,cowboy,uuid,jiffy,pixel"

init_code="[io:format(\"~p~n\", [application:start(A)]) || A <- [$apps]]."

erl -sname pixel@localhost -setcookie pixel -pa $PWD/deps/*/ebin \
    -pa $PWD/ebin -config sync -eval "$init_code"
