---

- name: ensure that nginx is installed
  sudo: yes
  apt: name=nginx state=present

- name: copy nxginx config file
  sudo: yes
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
