---
# Handlers

- name: restart ssh
  service: name=ssh state=restarted

- name: apply new iptables
  shell: iptables-restore < /etc/iptables/rules

- name: restart fail2ban
  service: name=fail2ban state=restarted
